version: "3"
services:
  db:
    image: mariadb:10.3
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./database/sample_dump.sql:/docker-entrypoint-initdb.d/dump.sql
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    links:
      - db
    volumes:
      - ./server/src:/usr/src/app/src
    command: npm run watch
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    env_file:
      - .env
    links:
      - server
    volumes:
      - ./client/src:/usr/src/app/src
    command: npm start
